api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/OwllabApp/Entity']
    eager_loading:
        enabled: true
    collection:
        pagination:
            items_per_page: 10
            client_items_per_page: true
            items_per_page_parameter_name: itemPerPage
            maximum_items_per_page: 20
            partial: false
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        OwllabApp\Exception\EmptyBodyException: 400
        OwllabApp\Exception\InvalidConfirmationTokenException: 404
