fos_user:
    db_driver: orm
    firewall_name: main
    user_class: NarmafzamApp\Bundle\ClinicBundle\Model\Entity\User
    from_email:
      address: "%env(resolve:MAILER_USER)%"
      sender_name: "%env(resolve:MAILER_USER)%"