controllers:
    resource: ../../src/OwllabApp/Controller/
    type: annotation
    prefix: /

easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation

api_platform:
    resource: .
    type: api_platform
    prefix: /api

api_login_check:
    path: /api/login_check
